### ISSUE TITLE
Converter for optimized SOFA files

### ISSUE THREAD

**Issue by isfmiho** [GrupoDiana/BRTLibrary#2]
It would be great to have a converter (eg. Matlab), that converts "any" HRTF SOFA file 
to a new SOFA file having the optimized structure, in order to have the shortest loading times in BeRTA.

The feature is helpful if you want to use the same HRTF set multiple times, but the loading and re-calculation take a lot of time. Pre-calculated HRTF files could save time.

**Comment by dgonzalezt** [comment]
We are working on it, we will have it soon.

**Comment by mariacuevas** [comment]
A set of Matlab scripts in a zip format has been included in the release: https://github.com/GrupoDiana/BRTLibrary/releases/tag/v1.1.0. Here you can find:
-  A **generator of grid orientations vector**. This script generates the orientations vector of the HRTF grid of BeRTA. 
- A **converter for optimized SOFA files**. This script generates an HRTF table already resampled with a configurable resamplingStep, i.e. the HRTF has been interpolated to meet our grid. This script generates the “Optimized HRTF table” that will allow the shortest loading time in BeRTA (as online interpolation will not need to be carried out).
