### ISSUE TITLE
BeRTA crashes on specific locations

### ISSUE THREAD

**Issue by isfmiho** [GrupoDiana/BRTLibrary#3]
These steps are crashing BeRTA:

- Load HRTF file from ARI database, I shared a specific file (BeRTA.sofa) in the attached zip file that causes the crash.
- Set the source direction to 0/0 (other directions do not crash). Use the distance of 1.2m. --> Set x/y/z positions to: 1,2/0/0.
- Load wav file (eg the one in the zip file)
- "play" command crashes BeRTA
- 2 OSC command log lists are shared in the zip file: one that causes crashing, and one that does not. They differ only in the source location. It should help you to reproduce the issue.

[BeRTA crashing.zip](https://github.com/GrupoDiana/BRTLibrary/files/12681045/BeRTA.crashing.zip) containing:
- BeRTA.sofa
- gaussiannoise2000ms10msfadeinout.wav
- OSC log crashing.txt
- OSC log not crashing.txt

**Comment by dgonzalezt** [comment]
It was a bug in the BRT library. It has been fixed in the library. 
Pending to build and upload new version of BeRTA (v1.5.1) with the bug fixed.

**Comment by dgonzalezt** [comment]
Bug fixed in release v1.1.0. Integrated in BeRTA version 1.6.0.
https://github.com/GrupoDiana/BRTLibrary/releases/tag/v1.1.0
