### ISSUE TITLE
BeRTA crashes in specific resampling rates in specific SOFA files (example attached)

### ISSUE THREAD

**Issue by isfmiho** [GrupoDiana/BRTLibrary#4]
Just loading the attached SOFA file crashes BeRTA, when setting the resampling rate to 10. 
When setting the resampling rate to 13 it works.

[latTestAziBeRTA.zip](https://github.com/GrupoDiana/BRTLibrary/files/12681092/latTestAziBeRTA.zip)

**Comment by dgonzalezt** [comment]
Working on it!

**Comment by dgonzalezt** [comment]
Bug fixed in release v1.1.0. Integrated in BeRTA version 1.6.0.
https://github.com/GrupoDiana/BRTLibrary/releases/tag/v1.1.0
